build:
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr21.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr22.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chrX.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr19.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr18.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr17.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr16.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr15.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr14.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr13.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr12.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr11.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr10.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr9.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr8.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr7.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr6.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr5.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr4.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr3.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr2.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr1.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/gv_pop11_sub2_chr20.json mongoprodspain:tmp/genomicVariations.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/genomicVariations.json --collection genomicVariations	
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/datasets.json mongoprodspain:tmp/datasets.json
	docker cp /data/vault/oriol/oriol_beacon_data/pop11_sub2/individuals.json mongoprodspain:tmp/individuals.json
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/datasets.json --collection datasets
	docker exec mongoprodspain mongoimport --jsonArray --uri "mongodb://root:example@127.0.0.1:27023/beacon?authSource=admin" --file /tmp/individuals.json --collection individuals
	docker exec beaconprodspain python /beacon/connections/mongo/reindex.py
	docker exec beaconprodspain python beacon/connections/mongo/extract_filtering_terms.py